{{- if .Values.dex.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "k8s-ldap.name" . }}
    chart: {{ template "k8s-ldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.dex.name }}
  name: {{ template "k8s-ldap.dex.fullname" . }}
type: Opaque
data:
  config.yaml: |-
    {{ toYaml .Values.dex.config | b64enc }}
{{- end -}}
