{{- if .Values.loginapp.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{ template "k8s-ldap.name" . }}
    chart: {{ template "k8s-ldap.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: {{ .Values.loginapp.name }}
  name: {{ template "k8s-ldap.loginapp.fullname" . }}
type: Opaque
data:
  config.yaml: |-
    {{ toYaml .Values.loginapp.config | b64enc }}
{{- end -}}
